### ISSUE TITLE
it is not working

### ISSUE THREAD

**Issue by Ashs3021** [deepakgouda/faceunlock#4]

**Comment by deepakgouda** [comment]
Could you please add some description? The bash script shall run in the background. Once you lock your PC, the code will start executing ```face_recog.py``` and the screen shall be unlocked.

**Comment by Ashs3021** [comment]
did all specified but it didn't work

**Comment by Ashs3021** [comment]
the bash script runs in back

**Comment by deepakgouda** [comment]
Do you get any error messages in the terminal where the bash script is running?

**Comment by Ashs3021** [comment]
nope
